// Code generated by protoc-gen-go. DO NOT EDIT.
// source: customer.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Customer struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Customer) Reset()         { *m = Customer{} }
func (m *Customer) String() string { return proto.CompactTextString(m) }
func (*Customer) ProtoMessage()    {}
func (*Customer) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{0}
}

func (m *Customer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Customer.Unmarshal(m, b)
}
func (m *Customer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Customer.Marshal(b, m, deterministic)
}
func (m *Customer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Customer.Merge(m, src)
}
func (m *Customer) XXX_Size() int {
	return xxx_messageInfo_Customer.Size(m)
}
func (m *Customer) XXX_DiscardUnknown() {
	xxx_messageInfo_Customer.DiscardUnknown(m)
}

var xxx_messageInfo_Customer proto.InternalMessageInfo

func (m *Customer) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Customer) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Customer) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Customer) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Customer) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type AddCustomersRequest struct {
	Customers            []*Customer `protobuf:"bytes,1,rep,name=customers,proto3" json:"customers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddCustomersRequest) Reset()         { *m = AddCustomersRequest{} }
func (m *AddCustomersRequest) String() string { return proto.CompactTextString(m) }
func (*AddCustomersRequest) ProtoMessage()    {}
func (*AddCustomersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{1}
}

func (m *AddCustomersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCustomersRequest.Unmarshal(m, b)
}
func (m *AddCustomersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCustomersRequest.Marshal(b, m, deterministic)
}
func (m *AddCustomersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCustomersRequest.Merge(m, src)
}
func (m *AddCustomersRequest) XXX_Size() int {
	return xxx_messageInfo_AddCustomersRequest.Size(m)
}
func (m *AddCustomersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCustomersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddCustomersRequest proto.InternalMessageInfo

func (m *AddCustomersRequest) GetCustomers() []*Customer {
	if m != nil {
		return m.Customers
	}
	return nil
}

type AddCustomersResponse struct {
	AddedCustomer        *Customer `protobuf:"bytes,1,opt,name=addedCustomer,proto3" json:"addedCustomer,omitempty"`
	Error                *Error    `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddCustomersResponse) Reset()         { *m = AddCustomersResponse{} }
func (m *AddCustomersResponse) String() string { return proto.CompactTextString(m) }
func (*AddCustomersResponse) ProtoMessage()    {}
func (*AddCustomersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{2}
}

func (m *AddCustomersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCustomersResponse.Unmarshal(m, b)
}
func (m *AddCustomersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCustomersResponse.Marshal(b, m, deterministic)
}
func (m *AddCustomersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCustomersResponse.Merge(m, src)
}
func (m *AddCustomersResponse) XXX_Size() int {
	return xxx_messageInfo_AddCustomersResponse.Size(m)
}
func (m *AddCustomersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCustomersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddCustomersResponse proto.InternalMessageInfo

func (m *AddCustomersResponse) GetAddedCustomer() *Customer {
	if m != nil {
		return m.AddedCustomer
	}
	return nil
}

func (m *AddCustomersResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Error struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{3}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Customer)(nil), "proto.Customer")
	proto.RegisterType((*AddCustomersRequest)(nil), "proto.AddCustomersRequest")
	proto.RegisterType((*AddCustomersResponse)(nil), "proto.AddCustomersResponse")
	proto.RegisterType((*Error)(nil), "proto.Error")
}

func init() { proto.RegisterFile("customer.proto", fileDescriptor_9efa92dae3d6ec46) }

var fileDescriptor_9efa92dae3d6ec46 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x95, 0xa4, 0x81, 0xe6, 0x0a, 0xad, 0x74, 0x74, 0xb0, 0x02, 0x43, 0x94, 0x29, 0x0b,
	0x1d, 0x82, 0xba, 0x22, 0x21, 0x60, 0x45, 0xc2, 0x7c, 0x02, 0x13, 0x1f, 0x10, 0xa9, 0xa9, 0x53,
	0x3b, 0x65, 0xe6, 0xa3, 0xa3, 0x5e, 0xe2, 0x56, 0x95, 0x32, 0xd9, 0xef, 0xfd, 0x9e, 0xee, 0x1f,
	0xcc, 0xab, 0xbd, 0xeb, 0x4c, 0x43, 0x76, 0xd5, 0x5a, 0xd3, 0x19, 0x8c, 0xf9, 0xc9, 0xff, 0x02,
	0x98, 0x3e, 0x0f, 0x04, 0xe7, 0x10, 0xd6, 0x5a, 0x04, 0x59, 0x50, 0x44, 0x32, 0xac, 0x35, 0xde,
	0x41, 0xf2, 0x55, 0x5b, 0xd7, 0xbd, 0xa9, 0x86, 0x44, 0x98, 0x05, 0x45, 0x22, 0x4f, 0x06, 0xa6,
	0x30, 0xdd, 0xa8, 0x01, 0x46, 0x0c, 0x8f, 0x1a, 0x97, 0x10, 0x53, 0xa3, 0xea, 0x8d, 0x98, 0x30,
	0xe8, 0xc5, 0xc1, 0x6d, 0x7f, 0xcc, 0x96, 0x44, 0xdc, 0xbb, 0x2c, 0xf2, 0x17, 0xb8, 0x79, 0xd2,
	0xda, 0x0f, 0xe1, 0x24, 0xed, 0xf6, 0xe4, 0x3a, 0xbc, 0x87, 0xc4, 0x8f, 0xec, 0x44, 0x90, 0x45,
	0xc5, 0xac, 0x5c, 0xf4, 0xb3, 0xaf, 0x7c, 0x56, 0x9e, 0x12, 0xf9, 0x0e, 0x96, 0xe7, 0x55, 0x5c,
	0x6b, 0xb6, 0x8e, 0x70, 0x0d, 0xd7, 0x4a, 0x6b, 0x3a, 0x12, 0x5e, 0x6f, 0xa4, 0xd4, 0x79, 0x0a,
	0x73, 0x88, 0xc9, 0x5a, 0x63, 0x79, 0xed, 0x59, 0x79, 0x35, 0xc4, 0x5f, 0x0f, 0x9e, 0xec, 0x51,
	0xbe, 0x86, 0x98, 0x35, 0x22, 0x4c, 0x2a, 0xa3, 0x89, 0x4b, 0x27, 0x92, 0xff, 0x28, 0xe0, 0xb2,
	0x21, 0xe7, 0xd4, 0xb7, 0xbf, 0x9c, 0x97, 0xe5, 0x3b, 0x2c, 0x7c, 0x9b, 0x0f, 0xb2, 0xbf, 0x75,
	0x45, 0xf8, 0x08, 0x91, 0xd2, 0x1a, 0xd3, 0xa1, 0xcb, 0xc8, 0x39, 0xd2, 0xdb, 0x51, 0xd6, 0x2f,
	0xf9, 0x79, 0xc1, 0xec, 0xe1, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x3d, 0x38, 0x87, 0xe5, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomerServiceClient is the client API for CustomerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomerServiceClient interface {
	Add(ctx context.Context, in *AddCustomersRequest, opts ...grpc.CallOption) (*AddCustomersResponse, error)
}

type customerServiceClient struct {
	cc *grpc.ClientConn
}

func NewCustomerServiceClient(cc *grpc.ClientConn) CustomerServiceClient {
	return &customerServiceClient{cc}
}

func (c *customerServiceClient) Add(ctx context.Context, in *AddCustomersRequest, opts ...grpc.CallOption) (*AddCustomersResponse, error) {
	out := new(AddCustomersResponse)
	err := c.cc.Invoke(ctx, "/proto.CustomerService/add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerServiceServer is the server API for CustomerService service.
type CustomerServiceServer interface {
	Add(context.Context, *AddCustomersRequest) (*AddCustomersResponse, error)
}

// UnimplementedCustomerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCustomerServiceServer struct {
}

func (*UnimplementedCustomerServiceServer) Add(ctx context.Context, req *AddCustomersRequest) (*AddCustomersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}

func RegisterCustomerServiceServer(s *grpc.Server, srv CustomerServiceServer) {
	s.RegisterService(&_CustomerService_serviceDesc, srv)
}

func _CustomerService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCustomersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CustomerService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).Add(ctx, req.(*AddCustomersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CustomerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CustomerService",
	HandlerType: (*CustomerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "add",
			Handler:    _CustomerService_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "customer.proto",
}
